/* tandy-tokenize.c		Front end for Model 100 BASIC tokenizer
 * 
 * This is just the frontend. 
 * For the actual tokenizer, see tandy-tokenize.lex.
 */

#include "lex.yy.c"		/* Generated by `flex tandy-tokenize.lex` */

int main(int argv, char *argc[]) {
  /*
   * Usage: ./tandy-tokenize  <FOO.DO  >FOO.BA
   * See also the "tokenize" shell script wrapper.
   */

  while (yylex())
    ;
  return 0;
}


int yywrap() {
  return 1;			/* Always only read one file */
}
