10 REM ERL Equals
20 REM ERL Less than
30 REM ERL Less than or equal to
40 REM ERL Greater than
50 REM ERL Greater than or equal to
60 REM Equals ERL
70 REM Less than ERL
80 REM Less than or equal to ERL
90 REM Greater than ERL
100 REM Greater than or equal to ERL
110 REM 110-
120 REM 120-130
130 REM 120-130
140 REM -140
150 REM ALL CATS ARE GREY
1010 IF ERL =  10 THEN PRINT "Equals works"
1020 IF ERL <  20 THEN PRINT "Less than works"
1030 IF ERL <= 30 THEN PRINT "Less than or equal works"
1040 IF ERL >  40 THEN PRINT "Greater than works"
1050 IF ERL >= 50 THEN PRINT "Greater than or equal works"
1060 IF ERL =  60 THEN PRINT "Equals works"
1070 IF ERL <  70 THEN PRINT "Less than works"
1080 IF ERL <= 80 THEN PRINT "Less than or equal works"
1090 IF ERL >  90 THEN PRINT "Greater than works"
1100 IF ERL >= 100 THEN PRINT "Greater than or equal works"
1110 LLIST 110 -
1120 LLIST 120 - 130
1130 LLIST -
1140 LLIST - 140
1150 GOTO 150
