220 REM Testing ' inside of ".
221 PRINT"Don't you? Single quote inside doubles"  'This comment disappears
223 PRINT"                    ,------*------,"
224 PRINT"    ,-------------   '---  ------'"
225 PRINT"     '-------- --'      / /"
226 PRINT"         ,---' '-------/ /--,"
227 PRINT"          '----------------'":PRINT
228 PRINT"    THE USS ENTERPRISE --- NCC-1701"
229 PRINT:PRINT:PRINT:PRINT:PRINT
230 PRINT "RESEARCHING THIS GALAXY . . .";
