name: release
# Mostly from https://jon.sprig.gs/blog/post/2442

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: make
      - name: Check
        run: make check
      - name: Create .tar.gz files
        run: make artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tokenize-source.tar.gz
            tokenize-cfiles.tar.gz
            tokenize-linux-amd64.tar.gz




